# Generated by Django 3.1.7 on 2021-03-26 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0007_auto_20210326_1813'),
        ('answer', '0001_initial'),
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.BooleanField(default=None)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('answer_id', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer', to='answer.answer')),
                ('emitter_profile', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emitterProfile', to='user_profile.userprofile')),
                ('question_id', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question', to='question.question')),
                ('receiver_profile', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiverProfile', to='user_profile.userprofile')),
            ],
        ),
    ]
