# Generated by Django 3.1.7 on 2021-03-26 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0007_auto_20210326_1813'),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a title', max_length=75)),
                ('content', models.TextField(help_text='Enter your question', max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('total_votes', models.IntegerField(default=0, help_text='Number of votes')),
                ('resolution', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='user_profile.userprofile')),
                ('tags', models.ManyToManyField(blank=True, related_name='questions', to='tag.Tag')),
            ],
        ),
    ]
