# Generated by Django 3.1.7 on 2021-03-26 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0007_auto_20210326_1813'),
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(default='', help_text='Resume of the content', max_length=60)),
                ('content', models.TextField(default='', help_text='Enter your answer', max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_votes', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='user_profile.userprofile')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='question.question')),
            ],
        ),
    ]
