# Generated by Django 3.1.2 on 2021-03-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20210326_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='error-pic.png', help_text='Choose a picture', upload_to='media/images/'),
        ),
    ]
