# Generated by Django 3.1.2 on 2021-03-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20210326_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar_profile',
            field=models.ImageField(null=True, upload_to='media/images/'),
        ),
    ]
