# Generated by Django 3.1.7 on 2021-03-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_auto_20210326_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pseudo',
            field=models.CharField(blank=True, default='Daniel', help_text='Enter your pseudo, Daniel', max_length=30, unique=True),
        ),
    ]
