# Generated by Django 3.1.7 on 2021-04-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_auto_20210401_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='biography',
            field=models.TextField(blank=True, help_text='Enter your brilliant biography', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pseudo',
            field=models.CharField(blank=True, help_text='Enter your pseudo, Daniel', max_length=30, null=True),
        ),
    ]
